name: build by force

on:
  #push:
  #  branches:
  #    - master
  #    - main
  workflow_dispatch:
  #repository_dispatch:
  #  types: apache

jobs:
  apache:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses apache
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="treehouses/apache"
          source .github/workflows/utils.sh
          echo "amd64"
          debian_x86_sha=$(get_variant_sha "debian" "latest" "amd64")
          echo $debian_x86_sha
          #variant_apache_x86_sha=$(get_manifest_sha "$repo:latest" "amd64")
          #echo $variant_apache_x86_sha
          echo "arm"
          balena_rpi_sha=$(get_tag_sha "balenalib/raspberry-pi-alpine" "latest")
          echo $balena_rpi_sha
          #variant_rpi_sha=$(get_manifest_sha "$repo:latest" "arm")
          #echo $variant_rpi_sha
          echo "arm64"
          debian_arm64_sha=$(get_variant_sha "debian" "latest" "arm64")
          echo $debian_arm64_sha
          #variant_apache_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          #echo $variant_apache_arm64_sha
          echo "change"
          flag=true #$(compare_sha  "$debian_x86_sha" "$variant_apache_x86_sha" "$balena_rpi_sha" "$variant_rpi_sha" "$debian_arm64_sha" "$variant_apache_arm64_sha")
          echo $flag
          if [[ $flag == true ]]; then
            echo "tags"
            tag="$(date +%Y%m%d%H%M)"
            echo $tag
            docker manifest create $repo:$tag $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
            docker manifest annotate $repo:$tag $repo-tags:amd64 --arch amd64
            docker manifest annotate $repo:$tag $repo-tags:arm64 --arch arm64
            docker manifest annotate $repo:$tag $repo-tags:arm --arch arm
            docker manifest inspect $repo:$tag
            docker manifest push $repo:$tag
            tag2="latest"
            echo $tag2
            docker manifest create $repo:$tag2 $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
            docker manifest annotate $repo:$tag2 $repo-tags:amd64 --arch amd64
            docker manifest annotate $repo:$tag2 $repo-tags:arm64 --arch arm64
            docker manifest annotate $repo:$tag2 $repo-tags:arm --arch arm
            docker manifest inspect $repo:$tag2
            docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi
